### ISSUE TITLE
Both Node-Red examples give debug error - TypeError: URLBrowserResolver is not a constructor

### ISSUE THREAD

**Issue by pzele** [ollixx/node-red-contrib-pdfmake#1]
Using both examples exactly as provided in Node-Red - simple pdf and image svg pdf.

Both examples give the debug error "TypeError: URLBrowserResolver is not a constructor".

Have tried in two browsers Chrome 84.0.4147.89 & FireFox 79.0
Windows 10 64 bit environment
Node-Red v 1.1.2 
Java 8 261 

Thanks

**Comment by Steve-Mcl** [comment]
same here (3 users - same error)

node-red forum thread for reference: https://discourse.nodered.org/t/contrib-pdfmake-node-help-please-getting-node-to-work/30867


EDIT...

I have raised an issue here: https://github.com/bpampuch/pdfmake/issues/2037 on the pdfmake repo.

**Comment by Steve-Mcl** [comment]
PDFMake has fixed this problem - it is pending release.

Once they update above v0.1.67 I suggest you update your `package.json` to request "pdfmake" version `"^0.1.67"`

In the mean time, to make your node work, you could update the `package.json` to target "pdfmake" version `"0.1.65"` (exclude the `^`)

**Comment by Steve-Mcl** [comment]
A fix to pdfmake had resolved this issue. @ollixx I strongly recommend you update this node to ensure your dependancy targets ^0.1.68 to prevent anyone encountering this again.

**Comment by ollixx** [comment]
Hey folks, thx for reporting and the hint. Will fix that asap updating the lib as suggested.
