### ISSUE TITLE
Use typedInputs to provide flexibility

### ISSUE THREAD

**Issue by Steve-Mcl** [ollixx/node-red-contrib-pdfmake#2]
Hi, currently you only permit `msg.payload` to be the source of doc spec for PDFMake

Would you consider adding to your UI a typedInputs that accepts msg and json (perhaps even flow and global) for the doc spec, options & output property?

this would permit users to easily specify which property of the msg to get the doc spec and where the output is sent (instead of having change nodes to juggle things around before & after).

the addition of json asn an input property permits a user to simply add a doc spec in the UI (good for testing) (see 2nd screen shot)

Here is the documentation for typedInput: https://nodered.org/docs/api/ui/typedInput/

This is what it might look like...
![image](https://user-images.githubusercontent.com/44235289/88904689-4b8bf680-d24d-11ea-8f0e-53a38ca89c50.png)

or

![image](https://user-images.githubusercontent.com/44235289/88904839-82620c80-d24d-11ea-9816-90df4921d0ee.png)

**Comment by ollixx** [comment]
Sure thing. Will do so this weekend.
I started with the minimal version as I needed the node for a project. Nice to see you people using it, so it'll be a pleasure to improve it.

**Comment by Steve-Mcl** [comment]
Thanks (I have a lot of ideas 😉) 

On this request - In particular, I would really like to see the input and output `msg` property implemented. 

I often chain nodes in series and hate having to use `change` nodes to shift `msg` properties in and out of payload (so that the payload output doesn't get overwritten by the next node in the chain) (hope that makes sense).

This is a function i use for setting the output msg property. it permits (for example) the user to enter `payload.reports.report1` and the function leaves everything in payload and payload.reports in-tact (even creates all none existing objects)...

```
/**
 * helper function to dynamically set a nested property by name
 * @param {*} obj - the object in which to set a properties value
 * @param {string} path - the path to the property e.g. payload.value
 * @param {*} val - the value to set in obj.path
 */
function setObjectProperty(obj, path, val){ 
    const keys = path.split('.');
    const lastKey = keys.pop();
    const lastObj = keys.reduce((obj, key) => 
        obj[key] = obj[key] || {}, 
        obj); 
    lastObj[lastKey] = val;
};
```  

Also note, it is convention in node-red that the input be called `property` and have an ellipsis icon (as I put in the mock UI in my original post)  - and- the return value be called `output` - but you are free to choose (I personally prefer `input` for the input - but thats just crazy talk man 😉)

Give me a shout on here or in the node-red forum as @Steve-Mcl if you need a hand with the typedInputs 👍 

--- 

#### EDIT...
I suspect suitable `typedInputs` setup + defaults might be ...

* Property (input)
  * Supported Types, `msg`, `flow`, `global`, `json` 
     NOTE: some might consider the inclusion of `flow` and `global` to be anti-pattern but options increase flexibility IMHO
  * Default Type: `msg`
  * Default Value: `payload`
* Options
  * Supported Types, `msg`, `flow`, `global`, `json`
   * Default Type: `json`
   * Default Value: `{}`
* Output Property
  * Supported Types, `msg` only
  * Default Type: `msg`
  * Default Value: `payload`

Thanks for indulging me :)

**Comment by ollixx** [comment]
Don't worry, I can handle your enthusiasm :-P
Thx for the extensive preparation. I will check your function, but I guess red.Utils.setMessageProperty() should do just that. I am familiar with typedInput. I use it in node-red-contrib-components, which ought to be my masterpiece, but until now is just a little more than a functional prototype.
I hope I can find some time this weekend...

**Comment by ollixx** [comment]
I created a PR branch with most of the requested features.
@Steve-Mcl : Would you like to check https://github.com/ollixx/node-red-contrib-pdfmake/tree/pr/2-use-typedinput-configuration out and give a try? Meanwhile I have to work on some cleaning up, like to i18n the help text etc. If you really feel like contributing, some tests would be great.... ;-)

**Comment by ollixx** [comment]
done with v1.1.0
